<?php

namespace asset;

class Currency{
    public static function currencies(){
        return $currencies = [
            'algeria' => ['name' => 'Algerian Dinar', 'code' => 'DZD'],
            'angola' => ['name' => 'Angolan Kwanza', 'code' => 'AOA'],
            'benin' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'botswana' => ['name' => 'Botswana Pula', 'code' => 'BWP'],
            'burkina_faso' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'burundi' => ['name' => 'Burundian Franc', 'code' => 'BIF'],
            'cabo_verde' => ['name' => 'Cape Verdean Escudo', 'code' => 'CVE'],
            'cameroon' => ['name' => 'Central African CFA franc', 'code' => 'XAF'],
            'central_african_republic' => ['name' => 'Central African CFA franc', 'code' => 'XAF'],
            'chad' => ['name' => 'Central African CFA franc', 'code' => 'XAF'],
            'comoros' => ['name' => 'Comorian Franc', 'code' => 'KMF'],
            'democratic_republic_of_the_congo' => ['name' => 'Congolese Franc', 'code' => 'CDF'],
            'djibouti' => ['name' => 'Djiboutian Franc', 'code' => 'DJF'],
            'egypt' => ['name' => 'Egyptian Pound', 'code' => 'EGP'],
            'equatorial_guinea' => ['name' => 'Central African CFA franc', 'code' => 'XAF'],
            'eritrea' => ['name' => 'Eritrean Nakfa', 'code' => 'ERN'],
            'eswatini' => ['name' => 'Swazi Lilangeni', 'code' => 'SZL'],
            'ethiopia' => ['name' => 'Ethiopian Birr', 'code' => 'ETB'],
            'gabon' => ['name' => 'Central African CFA franc', 'code' => 'XAF'],
            'gambia' => ['name' => 'Gambian Dalasi', 'code' => 'GMD'],
            'ghana' => ['name' => 'Ghanaian Cedi', 'code' => 'GHS'],
            'guinea' => ['name' => 'Guinean Franc', 'code' => 'GNF'],
            'guinea-bissau' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'ivory_coast' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'kenya' => ['name' => 'Kenyan Shilling', 'code' => 'KES'],
            'lesotho' => ['name' => 'Lesotho Loti', 'code' => 'LSL'],
            'liberia' => ['name' => 'Liberian Dollar', 'code' => 'LRD'],
            'libya' => ['name' => 'Libyan Dinar', 'code' => 'LYD'],
            'madagascar' => ['name' => 'Malagasy Ariary', 'code' => 'MGA'],
            'malawi' => ['name' => 'Malawian Kwacha', 'code' => 'MWK'],
            'mali' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'mauritania' => ['name' => 'Mauritanian Ouguiya', 'code' => 'MRU'],
            'mauritius' => ['name' => 'Mauritian Rupee', 'code' => 'MUR'],
            'morocco' => ['name' => 'Moroccan Dirham', 'code' => 'MAD'],
            'mozambique' => ['name' => 'Mozambican Metical', 'code' => 'MZN'],
            'namibia' => ['name' => 'Namibian Dollar', 'code' => 'NAD'],
            'niger' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'nigeria' => ['name' => 'Nigerian Naira', 'code' => 'NGN'],
            'rwanda' => ['name' => 'Rwandan Franc', 'code' => 'RWF'],
            'sao_tome_and_principe' => ['name' => 'São Tomé and Príncipe Dobra', 'code' => 'STN'],
            'senegal' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'seychelles' => ['name' => 'Seychellois Rupee', 'code' => 'SCR'],
            'sierra_leone' => ['name' => 'Sierra Leonean Leone', 'code' => 'SLL'],
            'somalia' => ['name' => 'Somali Shilling', 'code' => 'SOS'],
            'south_africa' => ['name' => 'South African Rand', 'code' => 'ZAR'],
            'south_sudan' => ['name' => 'South Sudanese Pound', 'code' => 'SSP'],
            'sudan' => ['name' => 'Sudanese Pound', 'code' => 'SDG'],
            'tanzania' => ['name' => 'Tanzanian Shilling', 'code' => 'TZS'],
            'togo' => ['name' => 'West African CFA franc', 'code' => 'XOF'],
            'tunisia' => ['name' => 'Tunisian Dinar', 'code' => 'TND'],
            'uganda' => ['name' => 'Ugandan Shilling', 'code' => 'UGX'],
            'zambia' => ['name' => 'Zambian Kwacha', 'code' => 'ZMW'],
            'zimbabwe' => ['name' => 'Zimbabwean Dollar', 'code' => 'ZWL'],
            'afghanistan' => ['name' => 'Afghan Afghani', 'code' => 'AFN'],
            'armenia' => ['name' => 'Armenian Dram', 'code' => 'AMD'],
            'azerbaijan' => ['name' => 'Azerbaijani Manat', 'code' => 'AZN'],
            'bahrain' => ['name' => 'Bahraini Dinar', 'code' => 'BHD'],
            'bangladesh' => ['name' => 'Bangladeshi Taka', 'code' => 'BDT'],
            'bhutan' => ['name' => 'Bhutanese Ngultrum', 'code' => 'BTN'],
            'brunei' => ['name' => 'Brunei Dollar', 'code' => 'BND'],
            'cambodia' => ['name' => 'Cambodian Riel', 'code' => 'KHR'],
            'china' => ['name' => 'Chinese Yuan', 'code' => 'CNY'],
            'cyprus' => ['name' => 'Euro', 'code' => 'EUR'],
            'georgia' => ['name' => 'Georgian Lari', 'code' => 'GEL'],
            'india' => ['name' => 'Indian Rupee', 'code' => 'INR'],
            'indonesia' => ['name' => 'Indonesian Rupiah', 'code' => 'IDR'],
            'iran' => ['name' => 'Iranian Rial', 'code' => 'IRR'],
            'iraq' => ['name' => 'Iraqi Dinar', 'code' => 'IQD'],
            'israel' => ['name' => 'Israeli New Shekel', 'code' => 'ILS'],
            'japan' => ['name' => 'Japanese Yen', 'code' => 'JPY'],
            'jordan' => ['name' => 'Jordanian Dinar', 'code' => 'JOD'],
            'kazakhstan' => ['name' => 'Kazakhstani Tenge', 'code' => 'KZT'],
            'kuwait' => ['name' => 'Kuwaiti Dinar', 'code' => 'KWD'],
            'kyrgyzstan' => ['name' => 'Kyrgyzstani Som', 'code' => 'KGS'],
            'laos' => ['name' => 'Laotian Kip', 'code' => 'LAK'],
            'lebanon' => ['name' => 'Lebanese Pound', 'code' => 'LBP'],
            'malaysia' => ['name' => 'Malaysian Ringgit', 'code' => 'MYR'],
            'maldives' => ['name' => 'Maldivian Rufiyaa', 'code' => 'MVR'],
            'mongolia' => ['name' => 'Mongolian Tugrik', 'code' => 'MNT'],
            'myanmar_(burma)' => ['name' => 'Myanmar Kyat', 'code' => 'MMK'],
            'nepal' => ['name' => 'Nepalese Rupee', 'code' => 'NPR'],
            'north_korea' => ['name' => 'North Korean Won', 'code' => 'KPW'],
            'oman' => ['name' => 'Omani Rial', 'code' => 'OMR'],
            'pakistan' => ['name' => 'Pakistani Rupee', 'code' => 'PKR'],
            'palestine' => ['name' => 'Israeli New Shekel', 'code' => 'ILS'],
            'philippines' => ['name' => 'Philippine Peso', 'code' => 'PHP'],
            'qatar' => ['name' => 'Qatari Rial', 'code' => 'QAR'],
            'saudi_arabia' => ['name' => 'Saudi Riyal', 'code' => 'SAR'],
            'singapore' => ['name' => 'Singapore Dollar', 'code' => 'SGD'],
            'south_korea' => ['name' => 'South Korean Won', 'code' => 'KRW'],
            'sri_lanka' => ['name' => 'Sri Lankan Rupee', 'code' => 'LKR'],
            'syria' => ['name' => 'Syrian Pound', 'code' => 'SYP'],
            'taiwan' => ['name' => 'New Taiwan Dollar', 'code' => 'TWD'],
            'tajikistan' => ['name' => 'Tajikistani Somoni', 'code' => 'TJS'],
            'thailand' => ['name' => 'Thai Baht', 'code' => 'THB'],
            'timor-leste' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'turkey' => ['name' => 'Turkish Lira', 'code' => 'TRY'],
            'turkmenistan' => ['name' => 'Turkmenistani Manat', 'code' => 'TMT'],
            'united_arab_emirates' => ['name' => 'United Arab Emirates Dirham', 'code' => 'AED'],
            'uzbekistan' => ['name' => 'Uzbekistani Som', 'code' => 'UZS'],
            'vietnam' => ['name' => 'Vietnamese Dong', 'code' => 'VND'],
            'yemen' => ['name' => 'Yemeni Rial', 'code' => 'YER'],
            'albania' => ['name' => 'Albanian Lek', 'code' => 'ALL'],
            'andorra' => ['name' => 'Euro', 'code' => 'EUR'],
            'austria' => ['name' => 'Euro', 'code' => 'EUR'],
            'belarus' => ['name' => 'Belarusian Ruble', 'code' => 'BYN'],
            'belgium' => ['name' => 'Euro', 'code' => 'EUR'],
            'bosnia_and_herzegovina' => ['name' => 'Bosnia and Herzegovina Convertible Mark', 'code' => 'BAM'],
            'bulgaria' => ['name' => 'Bulgarian Lev', 'code' => 'BGN'],
            'croatia' => ['name' => 'Croatian Kuna', 'code' => 'HRK'],
            'czech_republic' => ['name' => 'Czech Koruna', 'code' => 'CZK'],
            'denmark' => ['name' => 'Danish Krone', 'code' => 'DKK'],
            'estonia' => ['name' => 'Euro', 'code' => 'EUR'],
            'finland' => ['name' => 'Euro', 'code' => 'EUR'],
            'france' => ['name' => 'Euro', 'code' => 'EUR'],
            'germany' => ['name' => 'Euro', 'code' => 'EUR'],
            'greece' => ['name' => 'Euro', 'code' => 'EUR'],
            'hungary' => ['name' => 'Hungarian Forint', 'code' => 'HUF'],
            'iceland' => ['name' => 'Icelandic Króna', 'code' => 'ISK'],
            'ireland' => ['name' => 'Euro', 'code' => 'EUR'],
            'italy' => ['name' => 'Euro', 'code' => 'EUR'],
            'kosovo' => ['name' => 'Euro', 'code' => 'EUR'],
            'latvia' => ['name' => 'Euro', 'code' => 'EUR'],
            'liechtenstein' => ['name' => 'Swiss Franc', 'code' => 'CHF'],
            'lithuania' => ['name' => 'Euro', 'code' => 'EUR'],
            'luxembourg' => ['name' => 'Euro', 'code' => 'EUR'],
            'malta' => ['name' => 'Euro', 'code' => 'EUR'],
            'moldova' => ['name' => 'Moldovan Leu', 'code' => 'MDL'],
            'monaco' => ['name' => 'Euro', 'code' => 'EUR'],
            'montenegro' => ['name' => 'Euro', 'code' => 'EUR'],
            'netherlands' => ['name' => 'Euro', 'code' => 'EUR'],
            'north_macedonia' => ['name' => 'Macedonian Denar', 'code' => 'MKD'],
            'norway' => ['name' => 'Norwegian Krone', 'code' => 'NOK'],
            'poland' => ['name' => 'Polish Złoty', 'code' => 'PLN'],
            'portugal' => ['name' => 'Euro', 'code' => 'EUR'],
            'romania' => ['name' => 'Romanian Leu', 'code' => 'RON'],
            'russia' => ['name' => 'Russian Ruble', 'code' => 'RUB'],
            'san_marino' => ['name' => 'Euro', 'code' => 'EUR'],
            'serbia' => ['name' => 'Serbian Dinar', 'code' => 'RSD'],
            'slovakia' => ['name' => 'Euro', 'code' => 'EUR'],
            'slovenia' => ['name' => 'Euro', 'code' => 'EUR'],
            'spain' => ['name' => 'Euro', 'code' => 'EUR'],
            'sweden' => ['name' => 'Swedish Krona', 'code' => 'SEK'],
            'switzerland' => ['name' => 'Swiss Franc', 'code' => 'CHF'],
            'ukraine' => ['name' => 'Ukrainian Hryvnia', 'code' => 'UAH'],
            'united_kingdom' => ['name' => 'British Pound Sterling', 'code' => 'GBP'],
            'vatican_city' => ['name' => 'Euro', 'code' => 'EUR'],
            'antigua_and_barbuda' => ['name' => 'Eastern Caribbean Dollar', 'code' => 'XCD'],
            'bahamas' => ['name' => 'Bahamian Dollar', 'code' => 'BSD'],
            'barbados' => ['name' => 'Barbadian Dollar', 'code' => 'BBD'],
            'belize' => ['name' => 'Belize Dollar', 'code' => 'BZD'],
            'canada' => ['name' => 'Canadian Dollar', 'code' => 'CAD'],
            'costa_rica' => ['name' => 'Costa Rican Colón', 'code' => 'CRC'],
            'cuba' => ['name' => 'Cuban Peso', 'code' => 'CUP'],
            'dominica' => ['name' => 'Eastern Caribbean Dollar', 'code' => 'XCD'],
            'dominican_republic' => ['name' => 'Dominican Peso', 'code' => 'DOP'],
            'el_salvador' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'grenada' => ['name' => 'Eastern Caribbean Dollar', 'code' => 'XCD'],
            'guatemala' => ['name' => 'Guatemalan Quetzal', 'code' => 'GTQ'],
            'haiti' => ['name' => 'Haitian Gourde', 'code' => 'HTG'],
            'honduras' => ['name' => 'Honduran Lempira', 'code' => 'HNL'],
            'jamaica' => ['name' => 'Jamaican Dollar', 'code' => 'JMD'],
            'mexico' => ['name' => 'Mexican Peso', 'code' => 'MXN'],
            'nicaragua' => ['name' => 'Nicaraguan Córdoba', 'code' => 'NIO'],
            'panama' => ['name' => 'Panamanian Balboa', 'code' => 'PAB'],
            'saint_kitts_and_nevis' => ['name' => 'Eastern Caribbean Dollar', 'code' => 'XCD'],
            'saint_lucia' => ['name' => 'Eastern Caribbean Dollar', 'code' => 'XCD'],
            'saint_vincent_and_the_grenadines' => ['name' => 'Eastern Caribbean Dollar', 'code' => 'XCD'],
            'trinidad_and_tobago' => ['name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD'],
            'united_states' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'argentina' => ['name' => 'Argentine Peso', 'code' => 'ARS'],
            'bolivia' => ['name' => 'Bolivian Boliviano', 'code' => 'BOB'],
            'brazil' => ['name' => 'Brazilian Real', 'code' => 'BRL'],
            'chile' => ['name' => 'Chilean Peso', 'code' => 'CLP'],
            'colombia' => ['name' => 'Colombian Peso', 'code' => 'COP'],
            'ecuador' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'guyana' => ['name' => 'Guyanese Dollar', 'code' => 'GYD'],
            'paraguay' => ['name' => 'Paraguayan Guarani', 'code' => 'PYG'],
            'peru' => ['name' => 'Peruvian Sol', 'code' => 'PEN'],
            'suriname' => ['name' => 'Surinamese Dollar', 'code' => 'SRD'],
            'uruguay' => ['name' => 'Uruguayan Peso', 'code' => 'UYU'],
            'venezuela' => ['name' => 'Venezuelan Bolívar', 'code' => 'VES'],
            'french_guiana' => ['name' => 'Euro', 'code' => 'EUR'],
            'australia' => ['name' => 'Australian Dollar', 'code' => 'AUD'],
            'fiji' => ['name' => 'Fijian Dollar', 'code' => 'FJD'],
            'kiribati' => ['name' => 'Australian Dollar', 'code' => 'AUD'],
            'marshall_islands' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'micronesia' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'nauru' => ['name' => 'Australian Dollar', 'code' => 'AUD'],
            'new_zealand' => ['name' => 'New Zealand Dollar', 'code' => 'NZD'],
            'palau' => ['name' => 'United States Dollar', 'code' => 'USD'],
            'papua_new_guinea' => ['name' => 'Papua New Guinean Kina', 'code' => 'PGK'],
            'samoa' => ['name' => 'Samoan Tala', 'code' => 'WST'],
            'solomon_islands' => ['name' => 'Solomon Islands Dollar', 'code' => 'SBD'],
            'tonga' => ['name' => 'Tongan Paanga', 'code' => 'TOP'],
            'tuvalu' => ['name' => 'Tuvaluan Dollar', 'code' => 'TVD'],
            'vanuatu' => ['name' => 'Vanuatu Vatu', 'code' => 'VUV'],
        ];
    }
}